# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Android Build

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.7'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Decode Keystore File
      run: echo "${{ secrets.KEYSTORE }}" | base64 -d > ${{ github.workspace }}/android/app/key.jks
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}

    - name: Build APK
      run: flutter build apk --release --flavor prod
      env:
        KEYSTORE_PASSWD: ${{ secrets.KEYSTORE_PASSWD }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}

    - name: Generate version tag
      id: version_tag
      run: |
        echo "VERSION_TAG=$(grep 'version: ' pubspec.yaml | sed 's/version: //' | cut -d '+' -f2)" >> $GITHUB_ENV
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION_TAG }}
        release_name: Build ${{ env.VERSION_TAG }}
        draft: false
        prerelease: false
    
    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/app/outputs/flutter-apk/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
    
    
