# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Android Build

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.7'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Decode Keystore File
      run: echo "${{ secrets.KEYSTORE }}" | base64 -d > ${{ github.workspace }}/android/app/key.jks
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}

    - name: Build APK
      run: flutter build apk --release --flavor prod
      env:
        KEYSTORE_PASSWD: ${{ secrets.KEYSTORE_PASSWD }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}

    - name: Generate version tag
      id: version_tag
      run: echo "VERSION_TAG=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-prod-release.apk
    
